---
apiVersion: v1
kind: Namespace
metadata:
  name: edge
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: edge
data:
  # Redis config
  SPRING_DATA_REDIS_HOST: "redis-test-master.databases.svc.cluster.local"
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_DATA_REDIS_TIMEOUT: "2000ms"

  # Security / Keycloak
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: "http://keycloak.109.69.17.82.nip.io/realms/iot-platform"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: "http://keycloak.109.69.17.82.nip.io/realms/iot-platform/protocol/openid-connect/certs"

  # Other services routes
  USER_SERVICE_URL: "http://user-service.apps.svc.cluster.local:80"
  DEVICE_SERVICE_URL: "http://device-service.apps.svc.cluster.local:80"
  ANALYTICS_SERVICE_URL: "http://analytics-service.apps.svc.cluster.local:80"
---
apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secret
  namespace: edge
type: Opaque
data:
  EXTERNAL_API_TOKEN: "bXktc3VwZXItc2VjcmV0LXBhc3N3b3Jk" # values MUST be base64 encoded
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  namespace: edge
spec:
  replicas: 1 # for start test
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
         app: api-gateway # how Deployment and Service find each others
    spec:
      containers:
        - name: gateway-container
          image: api-gateway:v2
          imagePullPolicy: Never # To user local images
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: api-gateway-config
            - secretRef:
                name: api-gateway-secret
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway # inside cluster DNS name for CoreDNS
  namespace: edge
spec:
  selector:
    app: api-gateway # where to send requests
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway-ingress
  namespace: edge
spec:
  ingressClassName: traefik
  rules:
    - host: "api.109.69.17.82.nip.io"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 80