apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: edge
data:
  # Redis config
  SPRING_DATA_REDIS_HOST: "redis-test-master.databases.svc.cluster.local"
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_DATA_REDIS_TIMEOUT: "2000ms"

  # Security / Keycloak
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: "http://keycloak.109.69.17.82.nip.io/realms/iot-platform"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: "http://keycloak.109.69.17.82.nip.io/realms/iot-platform/protocol/openid-connect/certs"

  # Other services routes
  USER_SERVICE_URL: "http://user-service.apps.svc.cluster.local:80"
  DEVICE_SERVICE_URL: "http://device-service.apps.svc.cluster.local:80"
  ANALYTICS_SERVICE_URL: "http://analytics-service.apps.svc.cluster.local:80"